### ISSUE TITLE
Problem with featured posts in Meta Stack Exchange

### ISSUE THREAD

**Issue by bernardoduarte** [StylishThemes/StackOverflow-Dark#198]
The font color is left black instead of turning it white as the style's default behavior.

* **Browser**: Chrome
* **Operating System**: Ubuntu
* **Link to page with the issue**: https://meta.stackexchange.com/questions/342991/planned-maintenance-scheduled-for-wednesday-february-5-2020-for-data-explorer
* **Screenshots**:
![image](https://user-images.githubusercontent.com/14969290/73305475-ec471e00-41f8-11ea-973c-8daab8d628c2.png)
![image](https://user-images.githubusercontent.com/14969290/73305531-0b45b000-41f9-11ea-87b0-94a0c9d7c750.png)

**Comment by bernardoduarte** [comment]
There is a hover event that turns it white, however that's not the default behavior of Meta Stack Exchange. So, perhaps just leave it white ;D
![image](https://user-images.githubusercontent.com/14969290/73305752-89a25200-41f9-11ea-853d-c34da057ee56.png)

**Comment by the-j0k3r** [comment]
The dark text was fixed yesterday,

>There is a hover event that turns it white, however that's not the default behavior of Meta Stack Exchange. So, perhaps just leave it white ;D

perhaps not =) its intended.

**Comment by Holt59** [comment]
@the-j0k3r  I have 4.1.3 and I still have this problem. Any idea?

**Comment by the-j0k3r** [comment]
> @the-j0k3r I have 4.1.3 and I still have this problem. Any idea?

Nope, afaik this is fixed and works across browsers, also just saying that you have same problem isnt actually helpful in determining the possible issue you face locally.

**Comment by Holt59** [comment]
@the-j0k3r Sorry, here is the bug issue template filled.

* **Browser**: Firefox 72.0.2
* **Operating System**: Windows 10
* **Link to page with the issue**: https://stackoverflow.com/ (any SO page)
* **Screenshot**: 

![image](https://user-images.githubusercontent.com/2393288/74023094-20f86980-499f-11ea-8313-38974d6e8e83.png)

I am using v4.1.3 with no customization.

**Comment by the-j0k3r** [comment]
This is me

Browser: Firefox 72.0.2
Operating System: Windows 10 version 1809

Im willing to bet you upgraded Windows to 1903 right? If so blame MS.

![Screenshot_2020-02-07 Stack Overflow - Where Developers Learn, Share, Build Careers](https://user-images.githubusercontent.com/31389848/74023258-85b3c400-499f-11ea-8c66-792a070791c9.png)

**Comment by Holt59** [comment]
@the-j0k3r I am on Windows 10 1809

![image](https://user-images.githubusercontent.com/2393288/74023468-0246a280-49a0-11ea-84ee-851c428589bd.png)

**Comment by the-j0k3r** [comment]
Here is the actual selectors

![Capture](https://user-images.githubusercontent.com/31389848/74023497-14284580-49a0-11ea-8cd9-8cd758737889.PNG)

> @the-j0k3r I am on Windows 10 1809

Then disable all other styles, that fails uninstall and re-install style.

**Comment by the-j0k3r** [comment]
Confirmed working: 

Firefox 72.0.2 64-bit
Firefox dev 73.0b12 (64-bit)
G-Chrome Version 79.0.3945.130 (Official Build) (64-bit)
G-Chrome Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by Holt59** [comment]
@the-j0k3r Sorry, I just noticed it is for `:visited` link only (I visited the three links so I did not notice the difference... ):

![image](https://user-images.githubusercontent.com/2393288/74026553-b8ad8600-49a6-11ea-8ad5-b79078f13ddd.png)

**Comment by the-j0k3r** [comment]
OK I can dupe it but I think it maybe fixed by adding those selectors. Bare with me.

**Comment by the-j0k3r** [comment]
OK try now.
